---

- name: Install system dependencies
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    state: latest
  with_items:
    - git

- name: Create the source code directory
  file:
    path: '{{ omeka_src }}'
    state: directory

- name: Pull Omeka from GitHub
  git:
    repo: '{{ omeka_repo }}'
    version: '{{ omeka_branch }}'
    dest: '{{ omeka_src }}'
    accept_hostkey: yes
    force: yes

- name: Set .htaccess
  command: cp .htaccess.changeme .htaccess
  args:
    chdir: '{{ omeka_src }}'

- name: Set config.yml
  command: cp config.ini.changeme config.ini
  args:
    chdir: '{{ omeka_src }}/application/config'

- name: Set db.ini
  template:
    src: db.ini.j2
    dest: '{{ omeka_src }}/db.ini'

- name: Clear default files
  when: omeka_files is defined
  file:
    path: '{{ omeka_src }}/files'
    state: absent

- name: Symlink files
  when: omeka_files is defined
  file:
    src: '{{ omeka_files }}'
    dest: '{{ omeka_src }}/files'
    state: link

- name: Set file permissions (local)
  when: omeka_files is not defined
  file:
    path: '{{ omeka_src }}/files'
    mode: 755
    recurse: yes

- name: Set file permissions (linked)
  when: omeka_files is defined
  file:
    path: '{{ omeka_files }}'
    mode: 755
    recurse: yes
